import { createElement } from "react";
import {
  ArrowLeftRight,
  BadgeDollarSign,
  BarChart3,
  Bell,
  BookOpen,
  Briefcase,
  Building2,
  CalendarCheck,
  CalendarDays,
  CalendarRange,
  CheckCircle2,
  Circle,
  ClipboardList,
  Coins,
  Contact,
  CreditCard,
  Crown,
  Database,
  DollarSign,
  Factory,
  FileBarChart,
  FileText,
  Gem,
  Globe,
  HandCoins,
  Home,
  Inbox,
  Key,
  LayoutDashboard,
  Layers,
  ListChecks,
  Lock,
  Mail,
  Megaphone,
  MessageSquare,
  Package,
  Percent,
  Receipt,
  Search,
  Settings,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  Star,
  Store,
  Tags,
  Target,
  TrendingUp,
  Truck,
  User,
  UserCog,
  Users,
  Wallet,
  Warehouse,
  Wrench,
  type LucideIcon,
} from "lucide-react";

export const ICON_MAP: Record<string, LucideIcon> = {
  ArrowLeftRight,
  BadgeDollarSign,
  BarChart3,
  Bell,
  BookOpen,
  Briefcase,
  Building2,
  CalendarCheck,
  CalendarDays,
  CalendarRange,
  CheckCircle2,
  ClipboardList,
  Coins,
  Contact,
  CreditCard,
  Crown,
  Database,
  DollarSign,
  Factory,
  FileBarChart,
  FileText,
  Gem,
  Globe,
  HandCoins,
  Home,
  Inbox,
  Key,
  Layers,
  LayoutDashboard,
  ListChecks,
  Lock,
  Mail,
  Megaphone,
  MessageSquare,
  Package,
  Percent,
  Receipt,
  Search,
  Settings,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  Star,
  Store,
  Tags,
  Target,
  TrendingUp,
  Truck,
  User,
  UserCog,
  Users,
  Wallet,
  Warehouse,
  Wrench,
};

export function resolveIcon(name: string | null | undefined): LucideIcon {
  if (!name) return Circle;
  return ICON_MAP[name] ?? Circle;
}

/**
 * Componente helper para renderizar un icono por nombre sin caer en la
 * regla `react-hooks/static-components` (que prohíbe asignar el resultado
 * de una función a una variable capitalizada y renderizarla inline).
 */
export function ResolvedIcon({
  name,
  className,
}: {
  name: string | null | undefined;
  className?: string;
}) {
  return createElement(resolveIcon(name), { className });
}
